# Logger
save_iter: 500                  # Frequency for saving weights and visualize result
save_iter_backup: 5000          # Frequency for saving backup weights
dir_weights: ./weights         # Path to weights folder

# Optimization
max_iter: 300000                # Maximum number of training iterations
batch_size: 4                   # Batch size
lr_gen: 0.0001                  # Generator learning rate
lr_dis: 0.0002                  # Discriminator learning rate

# Generator loss weighting
loss:
  w_adv: 0.03                    # Adversarial loss of discriminator 1
  w_adv2: 0.03                   # Adversarial loss of discriminator 2    
  w_recon: 1                     # Reconstruction loss
  w_hc: 0.3                      # Hair consistency loss
  w_cyc: 0.5                     # Cyclic loss
  w_emb1: 0.1                    # Embeddings loss
  w_emb2: 0.1                    # Relativistic distance loss
  w_pl: 0.01                     # Perceptual loss
  w_sl: 0.02                     # Semantic consistency loss

# Model options
identity_extractor: ir50_hybrid # Feature extraction network
input_size: 224                 # Image input size
latent_dim: 512                 # Latent embedding dimension of identity extractor
nc_in: 3                        # Number of input channel

# Dataset
dir_data: ./data/trn_data      # Path to dataset folder