# Logger
dir_weights: ./weights         # Path to weights folder

# Model options
identity_extractor: inceptionresnetv1 # Feature extraction network
input_size: 224                 # Image input size
latent_dim: 512                 # Latent embedding dimension of identity extractor
separate_adain: true
additional_emb: true            # Use source face embeddings as additional conditioning input
nc_in: 3                        # Number of input channel